### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by saimouli** [stereolabs/zed-oculus#1]
The code is compiling, however no output is shown on the screen 
![original](https://cloud.githubusercontent.com/assets/14081959/14212885/ffe8be76-f802-11e5-9d5f-7c8ce6db4bec.jpg)

**Comment by Hokbras** [comment]
Hi,

Some basic questions:
- Did you install the last Oculus Runtime ? With the Oculus Home, etc
- if yes, did you enable downloads from unknown sources in the Oculus Home ? (see [https://support.oculus.com/878170922281071](https://support.oculus.com/878170922281071))
- if yes, did the Oculus Home automatically runs on startup of the application ?
- if yes, check in your Rift if something appears. There should be a white scene which asks you to validate before to run the app. Validate it (press A with the xbox controller or focus the headset cursor on it for few seconds)

Did it solve your problem? Since the new sdk and the new runtime, each Oculus application isn't rendered unless the user validates the application from the Rift.

**Comment by saimouli** [comment]
After 5 minutes the .exe closes and states that "auto calibration failed." Does that mean zed is not calibrating? When running hello world zed, 1 out of 5 times zed couldn't calibrate

**Comment by saimouli** [comment]
.exe stopped stating "auto calibration failed". By installing the zed sdk 0.9.3 beta, fixed the issue. However, I'm getting this new error message 
![capture](https://cloud.githubusercontent.com/assets/14081959/14218564/ef55be04-f822-11e5-87b3-2db75c7d6223.PNG)

I don't think there is oculus home for SDK 0.8 beta.

**Comment by Hokbras** [comment]
Ok, I thought you were working with the new Oculus SDK 1.3.
Did you check the value of the variable _usefulWidth_ ? I think it's zero for you. So, there is an issue in the computation of this variable. Did you check the values _zed->getImageSize().width_ and _ovrFovH_ ? May you check where the computation is false?

I see in your previous post that you're compiling in _Debug Mode_, did you try in _Release Mode_ ?

**Comment by saimouli** [comment]
Thanks for replying. Yes, I noticed that usefulWidth=0. When I debugged values, I got the following:
ovrValue: 6434, zedFovH:-1.#IND, zed->getImagesize().width: 1280. 

UPDATE:
So, when I didn't include zedFovH from the calculations of usefulWidth. It gives this, with no video output. Do you think the main issue is because of the zedFovH is not working? If so, how should I proceed?

Thanks
![capture](https://cloud.githubusercontent.com/assets/14081959/14396054/68df45bc-fda3-11e5-9bc9-ff8684b1b5fd.PNG)

Yes, I tried with release. I get the same output

**Comment by Hokbras** [comment]
There is something wrong with the focal value that returns zed->getParameters()->LeftCam.fx. But if you set _widthGL_  to 1.0f and _heightGL_ to 0.5f, you should have the ZED output displayed in the rift with a wrong FOV.
Does the ZED Depth Viewer tool work for you? ZED SDK's samples?

**Comment by saimouli** [comment]
Most of the time Zed Depth Viewer doesn't work. It opens, but doesn't display any video on it and if it does, only the side by side works. Is this SDK problem? Do you want me to install another version?

**Comment by Hokbras** [comment]
Okay. The problem doesn't come from the sample ZED-Oculus. So yes, there is something wrong with the SDK (or your config or both).
Make sure your ZED isn't too close to a surface/object otherwise ZED's autocalibration fails.
Can you try this at line 127:
`sl::zed::ERRCODE zederr = zed->init(sl::zed::MODE::PERFORMANCE, 0, true, false, true);`
It disables the autocalibration process. It isn't a good thing to do but it helps for debugging. Contact our support team at support@stereolabs.com. Describe them your config, which tool works or not, how, etc. Where and how is your the ZED when you're running these application.

Hope your problem will be resolved soon.

**Comment by Hokbras** [comment]
Is your issue resolved? :)

**Comment by saimouli** [comment]
Yes, it has been solved. What I did was uninstalled whole SDK completely from system and installed 0.9.3 beta version

**Comment by Hokbras** [comment]
Great. Thank you for sharing how you resolved your issue.

Best.

**Comment by saimouli** [comment]
@AntonyML Do you think this code will work for pre recorded video from zed camera?In order to make it work, could you please suggest edits?

**Comment by saimouli** [comment]
[main_live.cpp.txt](https://github.com/stereolabs/zed-oculus/files/486087/main_live.cpp.txt)

**Comment by Hokbras** [comment]
Hi @saimouli . Yes, it will. However, I have to warn you that it would be very uncomfortable for the user if the ZED camera is moving in the recorded video.

To make it works, just follow how it's done in the other ZED SDK's samples. (eg: [https://github.com/stereolabs/zed-opencv/blob/master/src/main.cpp#L100](https://github.com/stereolabs/zed-opencv/blob/master/src/main.cpp#L100) )

Next time, open a new issue ;)

**Comment by saimouli** [comment]
Thanks, I'll take a look in to it. Sorry, I'll do it next time.
